### ISSUE TITLE
BUG - Create storage button does not work

### ISSUE THREAD

**Issue by Oliv4945** [berkutta/parts_manager#4]
`create` button on `storage` page is a link to https://XXXXX/components/create instead of https://XXXXX/storages/create

**Comment by berkutta** [comment]
Thanks, this already got fixed :) I recommend using the docker container of parts_manager together with the watchtower container, then you'll automatically get the container updated.

https://github.com/berkutta/parts_manager/commit/08c78ae3f0e952c23530a12d316ffeae522488e6

**Comment by Oliv4945** [comment]
Updated, thanks !
I am using it in Docker but I do not know an option in >atchover to track a Git repository and rebuild the image, the only option is to track Docker registry. Did you setup one ? 
Are you using this [Watchover](https://github.com/v2tec/watchtower) ?

**Comment by berkutta** [comment]
You don't need to rebuild it. That is already happening in the "docker cloud". When I push new code to master on git it automatically triggers a build process in the "docker cloud". When you have the v2tec watchtower container on your system it automatically checks every I think 5 minutes if a newer build is available and installs it.

**Comment by Oliv4945** [comment]
Oh, I read the instructions to quickly... You have set up a docker hub :)
I'll use it instead ! thanks
