### ISSUE TITLE
Idea - Add price field

### ISSUE THREAD

**Issue by Oliv4945** [berkutta/parts_manager#5]
It would be nice to have a price field, so we know at first glance if we can use the component for magic smoke or take care of it :)

**Comment by berkutta** [comment]
What do you think about a general attribute option per component like in the screenshot? Also with moving the datasheet link field to those free definable attributes.

![image](https://user-images.githubusercontent.com/11159719/51121311-6c315e80-1817-11e9-9fb6-0254f495f4ed.png)

**Comment by Oliv4945** [comment]
Wow, perfect ! I need to test it :)
So we can close :)

**Comment by berkutta** [comment]
Attributes added with https://github.com/berkutta/parts_manager/commit/61053445a03432b221167b8b6478e668e4214fce
