### ISSUE TITLE
Delete component ?

### ISSUE THREAD

**Issue by Oliv4945** [berkutta/parts_manager#6]
Hi,
I played a bit more with parts manager, creating testing components: is there any way to delete them yet ? I did not find it.
Thanks :)

**Comment by berkutta** [comment]
Fixed with https://github.com/berkutta/parts_manager/commit/a91c9a2e598745a655bd0995b3118458de62d05d & https://github.com/berkutta/parts_manager/commit/6eea7718baafd51144471fb4e350ed5c5fde5e6c
